[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "simulater-emr-analysis"
authors = [{name = "Ankit Arni, Brandon Lim, Luke Davies", email = ""}]
dynamic = ["version", "description"]
